### ISSUE TITLE
AV for second request

### ISSUE THREAD

**Issue by delphicz** [onryldz/express#1]
Great library. 
I created demo based on readme
  [Location('api/test')] // this optional
  TTest = class(TProvider)
  public
    [GET] [DEFAULT] // default attribute is optional.
    function Multiply(A, B: Integer): Integer;
 end;

and accessed from web browser, with http://localhost:8080/api/test/Multiply/10/20 
and for first time get correct  200. When pressed F5 I get Access Violation in Express.pas in ClassDelegate when Values.Free.
I tested with XE8 and Seattle.

**Comment by onryldz** [comment]
Hi, 
Thank you for feedback.
I did not create this issue. Can you send me call-stack? pls!

**Comment by delphicz** [comment]
Hi,
 
thank you for reply.
 
 
 
http://localhost:8080/api/test/Multiply/10/20
and F5
 
project is in attachment
 
 
 
 
 
 
System.SysFreeMem(???)
:00405939 SysFreeMem + $81
System._IntfClear(???)
:0040d083 @IntfClear + $13
System.TObject.Free
Express.ClassDelegate$55$ActRec.$0$Body($2CFB170,$2D013F0) ------------------------- Line 843
Express.TExpressApp.Call($2D11730,$2D26688)
WebModuleUnit2.TWebModule2.WebModule2DefaultHandlerAction($2D35610,$2D11730,$2D26688,True)
Web.HTTPApp.TWebActionItem.DispatchAction(???,$2D26688,True)
Web.HTTPApp.TCustomWebDispatcher.DispatchAction($2D11730,$2D26688)
Web.HTTPApp.TCustomWebDispatcher.HandleRequest(???,???)
Web.HTTPApp.TDefaultWebAppServices.InvokeDispatcher
Web.HTTPApp.TDefaultWebAppServices.HandleRequest
Web.WebReq.TWebRequestHandler.HandleRequest($2D11730,$2D26688)
IdHTTPWebBrokerBridge.TIdHTTPWebBrokerBridgeRequestHandler.Run(???,$2C728D0,???)
IdHTTPWebBrokerBridge.TIdHTTPWebBrokerBridge.DoCommandGet(???,???,$2C536E0)
IdCustomHTTPServer.TIdCustomHTTPServer.DoExecute($2D41CD0)
IdContext.TIdContext.Run
IdTask.TIdTask.DoRun
IdThread.TIdThreadWithTask.Run
IdThread.TIdThread.Execute
System.Classes.ThreadProc($2C691F0)
System.ThreadWrapper($2D013F0)
:7687338a kernel32.BaseThreadInitThunk + 0x12
:77519f72 ntdll.RtlInitializeExceptionChain + 0x63
:77519f45 ntdll.RtlInitializeExceptionChain + 0x36

**Comment by bikdikrik23** [comment]
I ran into the same problem... Did you figure out what the problem was?
